docs deployment

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -2,7 +2,7 @@
 
 if [ -z "$ENV" ]; then
   echo "💁‍♀️ Usage: ENV=staging npm run deploy"
-  echo "(or as appropriate)"
+  echo "(or production, note: not prod)"
   echo
   rm -rf ./dist
   exit 1
@@ -11,17 +11,26 @@ fi
 if [ $ENV == "staging" ]
 then
   FOLDER=docs-staging
+  BRANCH=develop
 elif [ $ENV == "production" ]
 then
   FOLDER=docs
-# Support our typical syntax
-elif [ $ENV == "prod" ]
-then
-  FOLDER=docs
+  BRANCH=main
 else
   echo "🤷‍♀️ Target unknown"
   exit 1
 fi
 
-rsync -av --delete --exclude '.git' --exclude '**/node_modules' ./docs/.vitepress/dist static@static.apostrophecms.com:/opt/static/$FOLDER &&
-echo "Synced up to $ENV"
+# We "deploy" to a subdirectory of the website repo now -Tom
+(
+  cd ~/apostrophecms/apostrophecms-website &&
+  { test -z "$(git status --porcelain)" || { echo "Error: Git working directory is not clean in apostrophecms-website"; false; }; } &&
+  git pull &&
+  git checkout $BRANCH
+) &&
+rsync -a ./docs/.vitepress/dist/ ~/apostrophecms/apostrophecms-website/public/docs &&
+(git add -A . && git commit -m 'docs deployment' && git push) &&
+echo "Pushed to ${branch} of apostrophecms/apostrophecms-website, a deployment should ensue."
+
+#rsync -av --delete --exclude '.git' --exclude '**/node_modules' ./docs/.vitepress/dist static@static.apostrophecms.com:/opt/static/$FOLDER &&
+#echo "Synced up to $ENV"
